#!/bin/bash
# 🧠 Auto-Learning System - Records lessons from dev sessions
# Part of the 3 Tigers Autonomous Development Framework

TIMESTAMP=$(date "+%Y-%m-%d_%H-%M")
LEARNINGS_DIR="/root/maw-workspace/ψ/memory/learnings"
SESSION_LOG="$LEARNINGS_DIR/auto_session_${TIMESTAMP}.md"
CODEX_SYNC="/root/maw-workspace/ψ/memory/codex_sync/sync_report.md"

mkdir -p "$LEARNINGS_DIR"

# 1. Git activity summary
GIT_COMMITS=$(cd /root/maw-workspace/soul-brews-web-core && git log --oneline --since="1 hour ago" 2>/dev/null | head -5)
GIT_CHANGED=$(cd /root/maw-workspace/soul-brews-web-core && git diff --stat HEAD~1 2>/dev/null | tail -1)

# 2. Resource snapshot
RAM_USAGE=$(free -m | awk '/^Mem:/ {printf "%d%%", $3*100/$2}')
CPU_LOAD=$(cat /proc/loadavg | awk '{print $1}')

# 3. Oracle Backend status
ORACLE_STATUS=$(curl -s --max-time 3 http://localhost:18088/health 2>/dev/null | grep -o '"fleet":"[^"]*"' | cut -d'"' -f4 || echo "offline")

# 4. Write session learning log
cat > "$SESSION_LOG" <<EOF
# 🧠 Auto-Learning Session: ${TIMESTAMP}

## System Snapshot
- **RAM**: $RAM_USAGE
- **CPU Load**: $CPU_LOAD
- **Oracle Fleet**: $ORACLE_STATUS

## Recent Git Activity
\`\`\`
$GIT_COMMITS
\`\`\`

## Changes Summary
$GIT_CHANGED

## Patterns Observed
- Session recorded automatically by 3 Tigers system
- All learnings synced to Soul Memory (ψ)

---
*Auto-generated by MAW Oracle Self-Learning Framework* 🔱🦉
EOF

echo "🧠 Learning session recorded: $SESSION_LOG"

# 5. Update Codex Sync Report
echo "[$TIMESTAMP] Session logged. Oracle: $ORACLE_STATUS | RAM: $RAM_USAGE" >> "$CODEX_SYNC"
